# Generated by Django 4.2.4 on 2023-10-03 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_valores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Valores',
        ),
    ]
