# Generated by Django 4.2.4 on 2023-11-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(max_length=30)),
                ('hora', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='horarios_disponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_nome', models.CharField(max_length=255)),
                ('prod_descricao', models.CharField(max_length=255)),
                ('prod_valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prod_destaque', models.BooleanField(default=False)),
                ('imagem', models.ImageField(null=True, upload_to='static/img/produtos/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_user', models.CharField(max_length=255)),
                ('client_password', models.CharField(max_length=128)),
                ('client_phone', models.CharField(max_length=13)),
                ('client_cep', models.CharField(max_length=255)),
                ('client_city', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corte_name', models.TextField(max_length=255)),
                ('corte_valor', models.FloatField(max_length=255)),
            ],
        ),
    ]
