# Generated by Django 4.0.6 on 2023-10-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_user', models.CharField(max_length=255)),
                ('client_password', models.CharField(max_length=128)),
                ('client_phone', models.CharField(max_length=13)),
                ('client_cep', models.CharField(max_length=255)),
                ('client_city', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corte_name', models.TextField(max_length=255)),
                ('corte_valor', models.FloatField(max_length=255)),
            ],
        ),
    ]
