# Generated by Django 4.2.4 on 2023-11-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('data_agendamento', models.DateTimeField()),
                ('agendado', models.BooleanField(default=False)),
            ],
        ),
    ]
