# Generated by Django 4.0.6 on 2023-10-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.FloatField(max_length=255)),
                ('destaque', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Horarios',
        ),
    ]
