# Generated by Django 4.0.6 on 2023-10-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0002_produtos_delete_horarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
