# Generated by Django 4.0.6 on 2023-10-11 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0003_contato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='descricao',
            new_name='prod_descricao',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='destaque',
            new_name='prod_destaque',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='nome',
            new_name='prod_nome',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='valor',
            new_name='prod_valor',
        ),
    ]
