# Generated by Django 4.2.4 on 2023-11-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0003_horariosdisponivel_delete_horarios_disponivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='nome',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='horario_agendamento',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='nome_cliente',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_agendamento',
            field=models.DateField(),
        ),
    ]
