# Generated by Django 4.0.6 on 2023-10-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0004_rename_descricao_produtos_prod_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='prod_destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='prod_valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
