# Generated by Django 4.2.6 on 2023-11-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0004_remove_agendamento_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='horario_agendamento',
            field=models.TimeField(default='00:00'),
        ),
    ]
