# Generated by Django 4.2.4 on 2023-10-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0005_alter_produtos_prod_destaque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(max_length=30)),
                ('hora', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='horarios_disponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
