# Generated by Django 4.2.6 on 2023-11-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0005_alter_agendamento_horario_agendamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='data_agendamento',
            new_name='id_data_agendamento',
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='email',
            new_name='id_email',
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='horario_agendamento',
            new_name='id_horario',
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='nome_cliente',
            new_name='id_nome',
        ),
    ]
