# Generated by Django 4.2.4 on 2023-11-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0006_horarios_horarios_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(default=False, upload_to='produtos/'),
        ),
    ]
