# Generated by Django 4.2.4 on 2023-11-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0007_produtos_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(default=None, upload_to='produtos/'),
        ),
    ]
