# Generated by Django 4.2.4 on 2024-10-12 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0007_rename_id_data_agendamento_agendamento_data_agendamento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horariosdisponivel',
            old_name='horario',
            new_name='horario_disponivel',
        ),
    ]
