# Generated by Django 4.2.4 on 2025-03-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0008_rename_horario_horariosdisponivel_horario_disponivel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horariosdisponivel',
            old_name='horario_disponivel',
            new_name='id_horario',
        ),
        migrations.AlterField(
            model_name='horarios',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='hora',
            field=models.TimeField(),
        ),
    ]
