# Generated by Django 4.2.4 on 2025-03-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0009_rename_horario_disponivel_horariosdisponivel_id_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='data',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='hora',
            field=models.TextField(max_length=10),
        ),
    ]
