# Generated by Django 4.2.4 on 2025-03-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0010_alter_horarios_data_alter_horarios_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='horario_agendamento',
            field=models.TimeField(),
        ),
    ]
