# Generated by Django 4.2.4 on 2025-03-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0011_alter_agendamento_horario_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='horario_agendamento',
            field=models.TimeField(default='00:00'),
        ),
    ]
