# Generated by Django 4.2.4 on 2025-03-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0012_alter_agendamento_horario_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarios',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='horario_agendamento',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='nome_cliente',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.DeleteModel(
            name='HorariosDisponivel',
        ),
    ]
