# Generated by Django 4.2.4 on 2023-11-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0012_alter_produtos_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/produtos/'),
        ),
    ]
