# Generated by Django 4.2.4 on 2025-03-22 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0013_horarios_disponivel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_inicio', models.TimeField(default=datetime.time(9, 0))),
                ('horario_fim', models.TimeField(default=datetime.time(17, 0))),
            ],
        ),
    ]
