# Generated by Django 4.2.4 on 2025-03-22 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0014_horarioatendimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorariosDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='HorarioAtendimento',
        ),
        migrations.RemoveField(
            model_name='horarios',
            name='disponivel',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='horario_agendamento',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='nome_cliente',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='data',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='hora',
            field=models.TextField(max_length=10),
        ),
        migrations.AddField(
            model_name='horariosdisponivel',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barberHome.horarios'),
        ),
    ]
