# Generated by Django 4.2.4 on 2025-03-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0015_horariosdisponivel_delete_horarioatendimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='horario_agendamento',
            field=models.TimeField(),
        ),
    ]
