# Generated by Django 4.2.4 on 2025-03-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0016_alter_agendamento_horario_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='valores',
            name='corte_valor',
            field=models.FloatField(),
        ),
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together={('data_agendamento', 'horario_agendamento')},
        ),
    ]
