# Generated by Django 4.2.4 on 2025-03-23 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0017_alter_horarios_data_alter_horarios_hora_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='horarios',
            index=models.Index(fields=['hora'], name='horarios_hora_idx'),
        ),
        migrations.AlterField(
            model_name='horariosdisponivel',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barberHome.horarios', to_field='hora'),
        ),
    ]