# Generated by Django 4.2.4 on 2025-03-23 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0018_alter_horarios_hora_alter_horariosdisponivel_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horariosdisponivel',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barberHome.horarios'),
        ),
        migrations.AddConstraint(
            model_name='horarios',
            constraint=models.UniqueConstraint(fields=('data', 'hora'), name='unique_data_hora'),
        ),
    ]
