# Generated by Django 4.2.4 on 2025-03-23 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0019_alter_horarios_hora_alter_horariosdisponivel_horario_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='horarios',
            name='horarios_hora_idx',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='agendado',
        ),
    ]
