# Generated by Django 4.2.4 on 2025-03-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0020_remove_horarios_horarios_hora_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariosdisponivel',
            name='horario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Valores',
        ),
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='imagem',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='agendado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='nome_cliente',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contato',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contato',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='prod_descricao',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='HorariosDisponivel',
        ),
    ]
