# Generated by Django 4.2.4 on 2025-03-23 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0021_remove_horariosdisponivel_horario_delete_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_user', models.CharField(max_length=255)),
                ('client_password', models.CharField(max_length=128)),
                ('client_phone', models.CharField(max_length=13)),
                ('client_cep', models.CharField(max_length=255)),
                ('client_city', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corte_name', models.TextField(max_length=255)),
                ('corte_valor', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(null=True, upload_to='static/img/produtos/'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='nome_cliente',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contato',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contato',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='prod_descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together={('data_agendamento', 'horario_agendamento')},
        ),
        migrations.CreateModel(
            name='HorariosDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barberHome.horarios')),
            ],
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='agendado',
        ),
    ]
