# Generated by Django 4.2.4 on 2025-03-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0022_usuario_valores_produtos_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='agendado',
            field=models.BooleanField(default=False),
        ),
    ]
