# Generated by Django 4.2.4 on 2025-03-24 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0023_agendamento_agendado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horarios',
            old_name='hora',
            new_name='horario',
        ),
    ]
