# Generated by Django 4.2.4 on 2025-03-24 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barberHome', '0024_rename_hora_horarios_horario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horarios',
            old_name='horario',
            new_name='hora',
        ),
    ]
